/* ========================================================================
 * Copyright 2014 
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.tenantcontrol.logic.ejb;

import java.util.List;

import co.edu.uniandes.csw.tenantcontrol.logic.dto.TenantControlDTO;
import co.edu.uniandes.csw.tenantcontrol.logic.dto.TenantControlPageDTO;
import co.edu.uniandes.csw.tenantcontrol.persistence.TenantControlPersistence;

public abstract class _TenantControlLogicService {

	protected TenantControlPersistence persistance;

	public TenantControlDTO createTenantControl(TenantControlDTO tenantControl){
		return persistance.createTenantControl( tenantControl); 
    }

	public List<TenantControlDTO> getTenantControls(){
		return persistance.getTenantControls(); 
	}

	public TenantControlPageDTO getTenantControls(Integer page, Integer maxRecords){
		return persistance.getTenantControls(page, maxRecords); 
	}

	public TenantControlDTO getTenantControl(Long id){
		return persistance.getTenantControl(id); 
	}

	public void deleteTenantControl(Long id){
	    persistance.deleteTenantControl(id); 
	}

	public void updateTenantControl(TenantControlDTO tenantControl){
	    persistance.updateTenantControl(tenantControl); 
	}	
}