/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlist.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListDTO;
import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListPageDTO;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.converter.WishListConverter;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.entity.WishListEntity;

public abstract class _WishListPersistence{

  	protected EntityManager entityManager;
        
	public WishListDTO createWishList(WishListDTO wishList) {
            entityManager.getTransaction().begin();
                WishListDTO persistedWishListDTO = existWishListBuyer(wishList.getBuyerId());
                if (persistedWishListDTO != null){
                    entityManager.getTransaction().commit();
                    return persistedWishListDTO;
                }
                else {
                    WishListEntity entity=WishListConverter.persistenceDTO2Entity(wishList);
                    entityManager.persist(entity);
                    entityManager.getTransaction().commit();
                    return WishListConverter.entity2PersistenceDTO(entity);   
                    
                }
	}
	
	@SuppressWarnings("unchecked")
	public List<WishListDTO> getWishLists() {
		entityManager.getTransaction().begin();
		Query q = entityManager.createQuery("select u from WishListEntity u");
		List<WishListDTO> result = WishListConverter.entity2PersistenceDTOList(q.getResultList());
		entityManager.getTransaction().commit();
		return result;
		
	}

	@SuppressWarnings("unchecked")
	public WishListPageDTO getWishLists(Integer page, Integer maxRecords) {
		entityManager.getTransaction().begin();
		Query count = entityManager.createQuery("select count(u) from WishListEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from WishListEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		WishListPageDTO response = new WishListPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(WishListConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}

	public WishListDTO getWishList(Long id) {
		entityManager.getTransaction().begin();
		WishListDTO result = WishListConverter.entity2PersistenceDTO(entityManager.find(WishListEntity.class, id));
		entityManager.getTransaction().commit();
		return result;
	}

	public void deleteWishList(Long id) {
		entityManager.getTransaction().begin();
		WishListEntity entity=entityManager.find(WishListEntity.class, id);
		entityManager.remove(entity);
		entityManager.getTransaction().commit();
	}
        
        public WishListDTO existWishListBuyer(Long wishBuyerId) {               
                List<WishListDTO> wishListDTO;
                Query q = entityManager.createQuery("select u from WishListEntity u where u.buyerId = '" + wishBuyerId + "'" );
                wishListDTO = WishListConverter.entity2PersistenceDTOList(q.getResultList());
                if (wishListDTO != null){
                    if (wishListDTO.size() > 0){
                        return wishListDTO.get(0);
                    }
                }                
                return null;
        }
        
        public Long getWishListIdBuyerId(Long wishBuyerId) {               
                List<WishListDTO> wishListDTO;
                Query q = entityManager.createQuery("select u from WishListEntity u where u.buyerId = '" + wishBuyerId + "'" );
                wishListDTO = WishListConverter.entity2PersistenceDTOList(q.getResultList());
                if (wishListDTO != null){
                    if (wishListDTO.size() > 0){
                        return wishListDTO.get(0).getId();
                    }
                }                
                return null;
        }
        
	public void updateWishList(WishListDTO detail) {
		entityManager.getTransaction().begin();
		WishListEntity entity=entityManager.merge(WishListConverter.persistenceDTO2Entity(detail));
		WishListConverter.entity2PersistenceDTO(entity);
		entityManager.getTransaction().commit();
	}

}