/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlist.persistence;

import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListDTO;
import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListPageDTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.shiro.SecurityUtils;

public class WishListPersistence extends _WishListPersistence{

    private EntityManagerFactory emf;

    public WishListPersistence() {
        emf = Persistence.createEntityManagerFactory("WishListPU");
    }

    public void getEntityManager() {
        co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO addressS = (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
        String tenant = addressS.getTenantID();
        Map<String, Object> emProperties = new HashMap<String, Object>();
        emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
        entityManager = emf.createEntityManager(emProperties);
    }
    
    @Override
    public WishListDTO createWishList(WishListDTO address) {
        WishListDTO address2;
        try {
            getEntityManager();
            address2 = super.createWishList(address);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            address2 = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address2;
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public List<WishListDTO> getWishLists() {
        List<WishListDTO> list;
        try {
            getEntityManager();
            list = super.getWishLists();
        } catch (Exception e) {
            list = new ArrayList<WishListDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public WishListPageDTO getWishLists(Integer page, Integer maxRecords) {
        WishListPageDTO pages;
        try {
            getEntityManager();
            pages = super.getWishLists(page, maxRecords);
        } catch (Exception e) {
            pages = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }
    
    @Override
    public WishListDTO getWishList(Long id) {
        WishListDTO address;
        try {
            getEntityManager();
            address = super.getWishList(id);
        } catch (Exception e) {
            address = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address;
    }
    
    @Override
    public void deleteWishList(Long id) {
        try {
            getEntityManager();
            super.deleteWishList(id);
        } catch (Exception e) {
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }
    
    @Override
    public void updateWishList(WishListDTO detail) {
        try {
            getEntityManager();
            super.updateWishList(detail);
        } catch (Exception e) {

        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public WishListDTO existWishListBuyer(Long wishBuyerId) {
        WishListDTO address;
        try {
            getEntityManager();
            address = super.existWishListBuyer(wishBuyerId);
        } catch (Exception e) {
            address = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address;
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public Long getWishListIdBuyerId(Long wishBuyerId) {
        Long address;
        try {
            getEntityManager();
            address = super.getWishListIdBuyerId(wishBuyerId);
        } catch (Exception e) {
            address = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address;
    }

}