/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.buyer.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.creditcard.persistence.entity.CreditCardEntity;
import co.edu.uniandes.csw.miso4204.buyer.persistence.entity.BuyerEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(BuyercreditCardEntityId.class)
@NamedQueries({
    @NamedQuery(name = "BuyercreditCardEntity.getByMasterId", query = "SELECT  u FROM BuyercreditCardEntity u WHERE u.buyerId=:buyerId"),
    @NamedQuery(name = "BuyercreditCardEntity.deleteBuyercreditCardEntity", query = "DELETE FROM BuyercreditCardEntity u WHERE u.buyerId=:buyerId and  u.creditCardId=:creditCardId")
})
public class BuyercreditCardEntity implements Serializable {

    @Id
    @Column(name = "buyerId")
    private Long buyerId;
    @Id
    @Column(name = "creditCardId")
    private Long creditCardId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "buyerId", referencedColumnName = "id")
    @JoinFetch
    private CreditCardEntity buyerIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "creditCardId", referencedColumnName = "id")
    @JoinFetch
    private CreditCardEntity creditCardIdEntity; 

    public BuyercreditCardEntity() {
    }

    public BuyercreditCardEntity(Long buyerId, Long creditCardId) {
        this.buyerId =buyerId;
        this.creditCardId = creditCardId;
    }

    public Long getBuyerId() {
        return buyerId;
    }

    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    public Long getCreditCardId() {
        return creditCardId;
    }

    public void setCreditCardId(Long creditCardId) {
        this.creditCardId = creditCardId;
    }

    public CreditCardEntity getBuyerIdEntity() {
        return buyerIdEntity;
    }

    public void setBuyerIdEntity(CreditCardEntity buyerIdEntity) {
        this.buyerIdEntity = buyerIdEntity;
    }

    public CreditCardEntity getCreditCardIdEntity() {
        return creditCardIdEntity;
    }

    public void setCreditCardIdEntity(CreditCardEntity creditCardIdEntity) {
        this.creditCardIdEntity = creditCardIdEntity;
    }

}
