/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.buyer.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.address.persistence.entity.AddressEntity;
import co.edu.uniandes.csw.miso4204.buyer.persistence.entity.BuyerEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(BuyeraddressEntityId.class)
@NamedQueries({
    @NamedQuery(name = "BuyeraddressEntity.getByMasterId", query = "SELECT  u FROM BuyeraddressEntity u WHERE u.buyerId=:buyerId"),
    @NamedQuery(name = "BuyeraddressEntity.deleteBuyeraddressEntity", query = "DELETE FROM BuyeraddressEntity u WHERE u.buyerId=:buyerId and  u.addressId=:addressId")
})
public class BuyeraddressEntity implements Serializable {

    @Id
    @Column(name = "buyerId")
    private Long buyerId;
    @Id
    @Column(name = "addressId")
    private Long addressId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "buyerId", referencedColumnName = "id")
    @JoinFetch
    private AddressEntity buyerIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "addressId", referencedColumnName = "id")
    @JoinFetch
    private AddressEntity addressIdEntity; 

    public BuyeraddressEntity() {
    }

    public BuyeraddressEntity(Long buyerId, Long addressId) {
        this.buyerId =buyerId;
        this.addressId = addressId;
    }

    public Long getBuyerId() {
        return buyerId;
    }

    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    public Long getAddressId() {
        return addressId;
    }

    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    public AddressEntity getBuyerIdEntity() {
        return buyerIdEntity;
    }

    public void setBuyerIdEntity(AddressEntity buyerIdEntity) {
        this.buyerIdEntity = buyerIdEntity;
    }

    public AddressEntity getAddressIdEntity() {
        return addressIdEntity;
    }

    public void setAddressIdEntity(AddressEntity addressIdEntity) {
        this.addressIdEntity = addressIdEntity;
    }

}
