/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/
define(['delegate/_buyerDelegate'], function() {
    App.Delegate.BuyerDelegate = App.Delegate._BuyerDelegate.extend({
        searchAddress: function(id, callback) {
            $.get("/buyer.web/webresources/buyers/" + id + "/address", function(data) {
                callback(data);
            });
         },
        searchPurchases: function(id, callback) {
            var dataList = [];
            
            var data1 = {};
            data1.id = 1;
            data1.name = "P1";
            data1.purchaseDate = "16/11/2014";
            data1.totalValue = 12000;
            data1.totalItems = 5;
            data1.points = 5;
            data1.buyerId = id;
            data1.addressId = 1;
            dataList.push(data1);
            
            var data2 = {};
            data2.id = 2;
            data2.name = "P2";
            data2.purchaseDate = "16/11/2014";
            data2.totalValue = 15000;
            data2.totalItems = 2;
            data2.points = 2;
            data2.buyerId = id;
            data2.addressId = 1;
            dataList.push(data2);
            
            var response = {};
            response.totalRecords = 2;
            response.records = dataList;
            callback(dataList);
            
            /*$.get("/purchase.services/webresources/purchases/buyer/" + id, function(data) {
                callback(data);
            });*/
         }
    });
});