/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.buyer.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.buyer.logic.dto.BuyerDTO;
import co.edu.uniandes.csw.miso4204.buyer.logic.dto.BuyerPageDTO;
import co.edu.uniandes.csw.miso4204.buyer.persistence.converter.BuyerConverter;
import co.edu.uniandes.csw.miso4204.buyer.persistence.entity.BuyerEntity;

public abstract class _BuyerPersistence{

  	protected EntityManager entityManager;
	
	public BuyerDTO createBuyer(BuyerDTO buyer) {
		BuyerEntity entity=BuyerConverter.persistenceDTO2Entity(buyer);
		entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
		return BuyerConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<BuyerDTO> getBuyers() {
		entityManager.getTransaction().begin();
		Query q = entityManager.createQuery("select u from BuyerEntity u");
		List<BuyerDTO> result = BuyerConverter.entity2PersistenceDTOList(q.getResultList());
		entityManager.getTransaction().commit();
		return result;
		
	}

	@SuppressWarnings("unchecked")
	public BuyerPageDTO getBuyers(Integer page, Integer maxRecords) {
		entityManager.getTransaction().begin();
		Query count = entityManager.createQuery("select count(u) from BuyerEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from BuyerEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		BuyerPageDTO response = new BuyerPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(BuyerConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}

	public BuyerDTO getBuyer(Long id) {
		entityManager.getTransaction().begin();
		BuyerDTO result = BuyerConverter.entity2PersistenceDTO(entityManager.find(BuyerEntity.class, id));
		entityManager.getTransaction().commit();
		return result;
	}

	public void deleteBuyer(Long id) {
		entityManager.getTransaction().begin();
		BuyerEntity entity=entityManager.find(BuyerEntity.class, id);
		entityManager.remove(entity);
		entityManager.getTransaction().commit();
	}

	public void updateBuyer(BuyerDTO detail) {
		entityManager.getTransaction().begin();
		BuyerEntity entity=entityManager.merge(BuyerConverter.persistenceDTO2Entity(detail));
		BuyerConverter.entity2PersistenceDTO(entity);
		entityManager.getTransaction().commit();
	}

}