/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.picture.persistence;

import co.edu.uniandes.csw.miso4204.picture.logic.dto.PictureDTO;
import co.edu.uniandes.csw.miso4204.picture.logic.dto.PicturePageDTO;
import co.edu.uniandes.csw.miso4204.picture.persistence.converter.PictureConverter;
import co.edu.uniandes.csw.miso4204.picture.persistence.entity.PictureEntity;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.apache.shiro.SecurityUtils;

public class PicturePersistence extends _PicturePersistence{
        private EntityManagerFactory emf;

	public PicturePersistence(){
		emf = Persistence.createEntityManagerFactory("PicturePU");
	}

        
        public void getEntityManager() {
          co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO pictureS = 
                  (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
          String tenant = pictureS.getTenantID();
          Map<String, Object> emProperties = new HashMap<String, Object>();
          emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
          entityManager = emf.createEntityManager(emProperties);
        }

    @Override
    public PictureDTO createPicture(PictureDTO picture) {
        PictureDTO picture2;
        try {
            getEntityManager();
            picture2 = super.createPicture(picture);
        } catch (Exception e) {
            e.printStackTrace();
            picture2 = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return picture2;
    }

    @Override
    @SuppressWarnings("unchecked")
    public List<PictureDTO> getPictures() {
        List<PictureDTO> list;
        try {
            getEntityManager();
            list = super.getPictures();
        } catch (Exception e) {
            e.printStackTrace();
            list = new ArrayList<PictureDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PicturePageDTO getPictures(Integer page, Integer maxRecords) {
        PicturePageDTO pages;
        try {
            getEntityManager();
            pages = super.getPictures(page, maxRecords);
        } catch (Exception e) {
            e.printStackTrace();
            pages = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }

    @Override
    public PictureDTO getPicture(Long id) {
        PictureDTO picture;
        try {
            getEntityManager();
            picture = super.getPicture(id);
        } catch (Exception e) {
            e.printStackTrace();
            picture = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return picture;
    }

    @Override
    public void deletePicture(Long id) {
        try {
            getEntityManager();
            super.deletePicture(id);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

    @Override
    public void updatePicture(PictureDTO detail) {
        try {
            getEntityManager();
            super.updatePicture(detail);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

    
    
        public List<PictureDTO> getPicturesSearch(Long product) 
        {
                // Armar la sentencia SQL
            List<PictureDTO> result = null;
            if (product == null) {
                return new ArrayList<PictureDTO>();
            }
            try {
                getEntityManager();        
                String sqlStatement = " select u.id, u.name, u.url " +
                                      " from PictureEntity u, ProductPictureEntity pp " +
                                      " where u.id = pp.pictureid " +
                                      "   and pp.productid = " + product; 
                
                
                Query q = entityManager.createNativeQuery(sqlStatement, PictureEntity.class);
		result = PictureConverter.entity2PersistenceDTOList(q.getResultList());
            } catch (Exception e) {
              e.printStackTrace();
              result = new ArrayList<PictureDTO>();
            } finally {
              if (entityManager.isOpen()) {
                entityManager.close();
              }
            }
	    return result;
        }        

}