/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlist.master.logic.ejb;

import co.edu.uniandes.csw.miso4204.wishlistitem.logic.dto.WishListItemDTO;
import co.edu.uniandes.csw.miso4204.wishlistitem.persistence.WishListItemPersistence;

import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListDTO;
import co.edu.uniandes.csw.miso4204.wishlist.master.logic.dto.WishListMasterDTO;
import co.edu.uniandes.csw.miso4204.wishlist.master.persistence.entity.WishListwhishListItemEntity;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.WishListPersistence;
import co.edu.uniandes.csw.miso4204.wishlist.master.persistence.WishListMasterPersistence;


public abstract class _WishListMasterLogicService {

 
    protected WishListPersistence wishlistPersistance;

    protected WishListMasterPersistence wishlistMasterPersistance;
   
    protected WishListItemPersistence wishListItemPersistance;

    public WishListMasterDTO createMasterWishList(WishListMasterDTO wishlist) {
        WishListDTO persistedWishListDTO = wishlistPersistance.createWishList(wishlist.getWishListEntity());
        if (wishlist.getCreatewhishListItem() != null) {
            for (WishListItemDTO wishListItemDTO : wishlist.getCreatewhishListItem()) {
                WishListItemDTO createdWishListItemDTO = wishListItemPersistance.createWishListItem(wishListItemDTO);
                WishListwhishListItemEntity wishlistWishListItemEntity = new WishListwhishListItemEntity(persistedWishListDTO.getId(), createdWishListItemDTO.getId());
                wishlistMasterPersistance.createWishListwhishListItemEntity(wishlistWishListItemEntity);
            }
        }
        // update wishListItem
        if (wishlist.getUpdatewhishListItem() != null) {
            for (WishListItemDTO wishListItemDTO : wishlist.getUpdatewhishListItem()) {
                wishListItemPersistance.updateWishListItem(wishListItemDTO);
                WishListwhishListItemEntity wishlistWishListItemEntity = new WishListwhishListItemEntity(persistedWishListDTO.getId(), wishListItemDTO.getId());
                wishlistMasterPersistance.createWishListwhishListItemEntity(wishlistWishListItemEntity);
            }
        }
        return wishlist;
    }

    public WishListMasterDTO getMasterWishList(Long id) {
        return wishlistMasterPersistance.getWishList(id);
    }

    public void deleteMasterWishList(Long id) {
        wishlistPersistance.deleteWishList(id);
    }

    public void updateMasterWishList(WishListMasterDTO wishlist) {
        wishlistPersistance.updateWishList(wishlist.getWishListEntity());

        //---- FOR RELATIONSHIP
        // persist new wishListItem
        if (wishlist.getCreatewhishListItem() != null) {
            for (WishListItemDTO wishListItemDTO : wishlist.getCreatewhishListItem()) {
                WishListItemDTO createdWishListItemDTO = wishListItemPersistance.createWishListItem(wishListItemDTO);
                WishListwhishListItemEntity wishlistWishListItemEntity = new WishListwhishListItemEntity(wishlist.getWishListEntity().getId(), createdWishListItemDTO.getId());
                wishlistMasterPersistance.createWishListwhishListItemEntity(wishlistWishListItemEntity);
            }
        }
        // update wishListItem
        if (wishlist.getUpdatewhishListItem() != null) {
            for (WishListItemDTO wishListItemDTO : wishlist.getUpdatewhishListItem()) {
                wishListItemPersistance.updateWishListItem(wishListItemDTO);
            }
        }
        // delete wishListItem
        if (wishlist.getDeletewhishListItem() != null) {
            for (WishListItemDTO wishListItemDTO : wishlist.getDeletewhishListItem()) {
                wishlistMasterPersistance.deleteWishListwhishListItemEntity(wishlist.getWishListEntity().getId(), wishListItemDTO.getId());
                wishListItemPersistance.deleteWishListItem(wishListItemDTO.getId());
            }
        }
    }
}
