/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.product.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.miso4204.product.logic.dto.ProductDTO;
import co.edu.uniandes.csw.miso4204.product.persistence.entity.ProductEntity;

public abstract class _ProductConverter {

	public static ProductDTO entity2PersistenceDTO(ProductEntity entity){
		if (entity != null) {
			ProductDTO dto = new ProductDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDescription(entity.getDescription());
					dto.setPrice(entity.getPrice());
					dto.setCategoryId(entity.getCategoryId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ProductEntity persistenceDTO2Entity(ProductDTO dto){
		if(dto!=null){
			ProductEntity entity=new ProductEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDescription(dto.getDescription());
			
					entity.setPrice(dto.getPrice());
			
					entity.setCategoryId(dto.getCategoryId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ProductDTO> entity2PersistenceDTOList(List<ProductEntity> entities){
		List<ProductDTO> dtos=new ArrayList<ProductDTO>();
		for(ProductEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ProductEntity> persistenceDTO2EntityList(List<ProductDTO> dtos){
		List<ProductEntity> entities=new ArrayList<ProductEntity>();
		for(ProductDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}