/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.buyer.logic.ejb;

import java.util.List;

import co.edu.uniandes.csw.miso4204.buyer.logic.dto.BuyerDTO;
import co.edu.uniandes.csw.miso4204.buyer.logic.dto.BuyerPageDTO;
import co.edu.uniandes.csw.miso4204.buyer.persistence.BuyerPersistence;

public abstract class _BuyerLogicService {

	protected BuyerPersistence persistance;

	public BuyerDTO createBuyer(BuyerDTO buyer){
		return persistance.createBuyer( buyer); 
    }

	public List<BuyerDTO> getBuyers(){
		return persistance.getBuyers(); 
	}

	public BuyerPageDTO getBuyers(Integer page, Integer maxRecords){
		return persistance.getBuyers(page, maxRecords); 
	}

	public BuyerDTO getBuyer(Long id){
		return persistance.getBuyer(id); 
	}

	public void deleteBuyer(Long id){
	    persistance.deleteBuyer(id); 
	}

	public void updateBuyer(BuyerDTO buyer){
	    persistance.updateBuyer(buyer); 
	}	
}