/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.user.persistence;

import co.edu.uniandes.csw.miso4204.security.logic.dto.UserSessionDTO;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.user.logic.dto.UserDTO;
import co.edu.uniandes.csw.miso4204.user.logic.dto.UserPageDTO;
import co.edu.uniandes.csw.miso4204.user.persistence.converter.UserConverter;
import co.edu.uniandes.csw.miso4204.user.persistence.entity.UserEntity;
import java.util.HashMap;
import java.util.Map;
import javax.persistence.FlushModeType;
import org.apache.shiro.SecurityUtils;
import org.eclipse.persistence.config.EntityManagerProperties;

public abstract class _UserPersistence{

  	protected EntityManager entityManager;
	
	public UserDTO createUser(UserDTO user) {                
		UserEntity entity=UserConverter.persistenceDTO2Entity(user);
		entityManager.getTransaction().begin();
                TenantSetup st = new TenantSetup(entityManager);
                st.setTenant(entityManager);
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
		return UserConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<UserDTO> getUsers() {
		entityManager.getTransaction().begin();
                TenantSetup st = new TenantSetup(entityManager);
                st.setTenant(entityManager);
		Query q = entityManager.createQuery("select u from UserEntity u");
		List<UserDTO> result = UserConverter.entity2PersistenceDTOList(q.getResultList());
		entityManager.getTransaction().commit();
		return result;
		
	}

	@SuppressWarnings("unchecked")
	public UserPageDTO getUsers(Integer page, Integer maxRecords) {
		entityManager.getTransaction().begin();
                TenantSetup st = new TenantSetup(entityManager);
                st.setTenant(entityManager);
		Query count = entityManager.createQuery("select count(u) from UserEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from UserEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		UserPageDTO response = new UserPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(UserConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}

	public UserDTO getUser(Long id) {
		entityManager.getTransaction().begin();
                TenantSetup st = new TenantSetup(entityManager);
                st.setTenant(entityManager);
		UserDTO result = UserConverter.entity2PersistenceDTO(entityManager.find(UserEntity.class, id));
		entityManager.getTransaction().commit();
		return result;
	}

	public void deleteUser(Long id) {
		entityManager.getTransaction().begin();
                TenantSetup st = new TenantSetup(entityManager);
                st.setTenant(entityManager);
		UserEntity entity=entityManager.find(UserEntity.class, id);
		entityManager.remove(entity);
		entityManager.getTransaction().commit();
	}

	public void updateUser(UserDTO detail) {
		entityManager.getTransaction().begin();
                TenantSetup st = new TenantSetup(entityManager);
                st.setTenant(entityManager);
		UserEntity entity=entityManager.merge(UserConverter.persistenceDTO2Entity(detail));
		UserConverter.entity2PersistenceDTO(entity);
		entityManager.getTransaction().commit();
	}

}