/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================


 Source generated by CrudMaker version 1.0.0.qualifier

 */
package co.edu.uniandes.csw.miso4204.user.persistence;

//import co.edu.uniandes.csw.miso4204.security.logic.dto.UserSessionDTO;
import co.edu.uniandes.csw.miso4204.user.logic.dto.UserDTO;
import co.edu.uniandes.csw.miso4204.user.logic.dto.UserPageDTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.shiro.SecurityUtils;

public class UserPersistence extends _UserPersistence {

    protected EntityManagerFactory emf;

    public UserPersistence() {
        emf = Persistence.createEntityManagerFactory("UserPU");
    }

    public void getEntityManager() {
        co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO userS = (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
        String tenant = userS.getTenantID();
        Map<String, Object> emProperties = new HashMap<String, Object>();
        emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
        entityManager = emf.createEntityManager(emProperties);
    }

    @Override
    public UserDTO createUser(UserDTO user) {
        UserDTO user2;
        try{
            getEntityManager();
            user2 = super.createUser(user);
        }
        catch(Exception e){
            e.printStackTrace();
            user2=null;
        }
        finally{
            if(entityManager.isOpen()){
                entityManager.close();
            }
        }
        return user2;
    }
    @Override
    @SuppressWarnings("unchecked")
    public List<UserDTO> getUsers() {
        List<UserDTO> list;
        try{
            getEntityManager();
            list = super.getUsers();
        }
        catch(Exception e){
            e.printStackTrace();
            list=new ArrayList<UserDTO>();
        }
        finally{
            if(entityManager.isOpen()){
                entityManager.close();
            }
        }
        return list;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserPageDTO getUsers(Integer page, Integer maxRecords) {
        UserPageDTO pages;
        try{
            getEntityManager();
            pages = super.getUsers(page, maxRecords);
        }
        catch(Exception e){
            e.printStackTrace();
            pages=null;
        }
        finally{
            if(entityManager.isOpen()){
                entityManager.close();
            }
        }
        return pages;
    }

    @Override
    public UserDTO getUser(Long id) {
        UserDTO user;
        try{
            getEntityManager();
            user = super.getUser(id);
        }
        catch(Exception e){
            e.printStackTrace();
            user=null;
        }
        finally{
            if(entityManager.isOpen()){
                entityManager.close();
            }
        }
        return user;
    }
    
    @Override
    public void deleteUser(Long id) {
        try{
            getEntityManager();
            super.deleteUser(id);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally{
            if(entityManager.isOpen()){
                entityManager.close();
            }
        }
    }

    @Override
    public void updateUser(UserDTO detail) {
        try{
            getEntityManager();
            super.updateUser(detail);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally{
            if(entityManager.isOpen()){
                entityManager.close();
            }
        }
    }

}
