/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.payment.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.payment.logic.dto.PaymentDTO;
import co.edu.uniandes.csw.miso4204.payment.logic.dto.PaymentPageDTO;
import co.edu.uniandes.csw.miso4204.payment.persistence.converter.PaymentConverter;
import co.edu.uniandes.csw.miso4204.payment.persistence.entity.PaymentEntity;

public abstract class _PaymentPersistence{

  	protected EntityManager entityManager;
	
	public PaymentDTO createPayment(PaymentDTO payment) {
		PaymentEntity entity=PaymentConverter.persistenceDTO2Entity(payment);
		entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
		return PaymentConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<PaymentDTO> getPayments() {
		entityManager.getTransaction().begin();
		Query q = entityManager.createQuery("select u from PaymentEntity u");
		List<PaymentDTO> result = PaymentConverter.entity2PersistenceDTOList(q.getResultList());
		entityManager.getTransaction().commit();
		return result;
		
	}

	@SuppressWarnings("unchecked")
	public PaymentPageDTO getPayments(Integer page, Integer maxRecords) {
		entityManager.getTransaction().begin();
		Query count = entityManager.createQuery("select count(u) from PaymentEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from PaymentEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		PaymentPageDTO response = new PaymentPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(PaymentConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}

	public PaymentDTO getPayment(Long id) {
		entityManager.getTransaction().begin();
		PaymentDTO result = PaymentConverter.entity2PersistenceDTO(entityManager.find(PaymentEntity.class, id));
		entityManager.getTransaction().commit();
		return result;
	}

	public void deletePayment(Long id) {
		entityManager.getTransaction().begin();
		PaymentEntity entity=entityManager.find(PaymentEntity.class, id);
		entityManager.remove(entity);
		entityManager.getTransaction().commit();
	}

	public void updatePayment(PaymentDTO detail) {
		entityManager.getTransaction().begin();
		PaymentEntity entity=entityManager.merge(PaymentConverter.persistenceDTO2Entity(detail));
		PaymentConverter.entity2PersistenceDTO(entity);
		entityManager.getTransaction().commit();
	}

}