/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.score.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.score.logic.dto.ScoreDTO;
import co.edu.uniandes.csw.miso4204.score.logic.dto.ScorePageDTO;
import co.edu.uniandes.csw.miso4204.score.persistence.converter.ScoreConverter;
import co.edu.uniandes.csw.miso4204.score.persistence.entity.ScoreEntity;

public abstract class _ScorePersistence{

  	protected EntityManager entityManager;
	
	public ScoreDTO createScore(ScoreDTO score) {
		ScoreEntity entity=ScoreConverter.persistenceDTO2Entity(score);
		entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
		return ScoreConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ScoreDTO> getScores() {
		entityManager.getTransaction().begin();
		Query q = entityManager.createQuery("select u from ScoreEntity u");
		List<ScoreDTO> result = ScoreConverter.entity2PersistenceDTOList(q.getResultList());
		entityManager.getTransaction().commit();
		return result;
		
	}

	@SuppressWarnings("unchecked")
	public ScorePageDTO getScores(Integer page, Integer maxRecords) {
		entityManager.getTransaction().begin();
		Query count = entityManager.createQuery("select count(u) from ScoreEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ScoreEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ScorePageDTO response = new ScorePageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ScoreConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}

	public ScoreDTO getScore(Long id) {
		entityManager.getTransaction().begin();
		ScoreDTO result = ScoreConverter.entity2PersistenceDTO(entityManager.find(ScoreEntity.class, id));
		entityManager.getTransaction().commit();
		return result;
	}

	public void deleteScore(Long id) {
		entityManager.getTransaction().begin();
		ScoreEntity entity=entityManager.find(ScoreEntity.class, id);
		entityManager.remove(entity);
		entityManager.getTransaction().commit();
	}

	public void updateScore(ScoreDTO detail) {
		entityManager.getTransaction().begin();
		ScoreEntity entity=entityManager.merge(ScoreConverter.persistenceDTO2Entity(detail));
		ScoreConverter.entity2PersistenceDTO(entity);
		entityManager.getTransaction().commit();
	}
        
	public ScorePageDTO getProductScores(Long productId) {
		entityManager.getTransaction().begin();

		Query q = entityManager.createQuery("select u from ScoreEntity u WHERE u.productscoreId=:productId");
                q.setParameter("productId", productId);
		ScorePageDTO response = new ScorePageDTO();
		response.setRecords(ScoreConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}
 
}