/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlist.master.persistence;
import co.edu.uniandes.csw.miso4204.wishlistitem.logic.dto.WishListItemDTO;
import co.edu.uniandes.csw.miso4204.wishlist.master.persistence.entity.WishListwhishListItemEntity;
import co.edu.uniandes.csw.miso4204.wishlistitem.persistence.converter.WishListItemConverter;
import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListDTO;
import co.edu.uniandes.csw.miso4204.wishlist.master.logic.dto.WishListMasterDTO;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.WishListPersistence;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.converter.WishListConverter;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.entity.WishListEntity;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;

public class _WishListMasterPersistence{

    protected EntityManager entityManager;
    
    protected WishListPersistence wishlistPersistence;  

    public WishListMasterDTO getWishList(Long wishlistId) {
        System.out.println("getWishList1");
        WishListMasterDTO wishlistMasterDTO = new WishListMasterDTO();
        System.out.println("getWishList2");
        if (wishlistPersistence == null){
            System.out.println("soy null");
        }
        else{
            System.out.println("no soy null");
        }
           try {
        WishListDTO wishlist = getWishListMaster(wishlistId);    
        System.out.println("getWishList3");
        wishlistMasterDTO.setWishListEntity(wishlist);
        System.out.println("getWishList4");
        wishlistMasterDTO.setListwhishListItem(getWishListwhishListItemEntityList(wishlistId));
        System.out.println("getWishList5");
        } catch (Exception e) {
                System.out.println(e.getMessage());
        }
        

        return wishlistMasterDTO;
    }

    public WishListwhishListItemEntity createWishListwhishListItemEntity(WishListwhishListItemEntity entity) {
        entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
        return entity;
    }

   public void deleteWishListwhishListItemEntity(Long wishListId, Long whishListItemId) {
		entityManager.getTransaction().begin();
        Query q = entityManager.createNamedQuery("WishListwhishListItemEntity.deleteWishListwhishListItemEntity");
        q.setParameter("wishListId", wishListId);
        q.setParameter("whishListItemId", whishListItemId);
        q.executeUpdate();
		entityManager.getTransaction().commit();
    }
   
    public WishListDTO getWishListMaster(Long id) {
        System.out.println("enPersisdewih1m");
            entityManager.getTransaction().begin();
            System.out.println("enPersisdewih2m");
            WishListDTO result = WishListConverter.entity2PersistenceDTO(entityManager.find(WishListEntity.class, id));
            System.out.println("enPersisdewih3m");
            entityManager.getTransaction().commit();
            System.out.println("enPersisdewih4m");
            return result;
    }

   public List<WishListItemDTO> getWishListwhishListItemEntityList(Long wishListId) {
		entityManager.getTransaction().begin();
		ArrayList<WishListItemDTO> resp = new ArrayList<WishListItemDTO>();
        Query q = entityManager.createNamedQuery("WishListwhishListItemEntity.getByMasterId");
        q.setParameter("wishListId",wishListId);
        List<WishListwhishListItemEntity> qResult =  q.getResultList();
        for (WishListwhishListItemEntity entity : qResult) { 
            if(entity.getWhishListItemIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(WishListItemConverter.entity2PersistenceDTO(entity.getWhishListItemIdEntity()));
        }
        entityManager.getTransaction().commit();
        return resp;
      
    }
 
}