/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.product.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.feature.persistence.entity.FeatureEntity;
import co.edu.uniandes.csw.miso4204.product.persistence.entity.ProductEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ProductfeatureEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ProductfeatureEntity.getByMasterId", query = "SELECT  u FROM ProductfeatureEntity u WHERE u.productId=:productId"),
    @NamedQuery(name = "ProductfeatureEntity.deleteProductfeatureEntity", query = "DELETE FROM ProductfeatureEntity u WHERE u.productId=:productId and  u.featureId=:featureId")
})
public class ProductfeatureEntity implements Serializable {

    @Id
    @Column(name = "productId")
    private Long productId;
    @Id
    @Column(name = "featureId")
    private Long featureId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "productId", referencedColumnName = "id")
    @JoinFetch
    private FeatureEntity productIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "featureId", referencedColumnName = "id")
    @JoinFetch
    private FeatureEntity featureIdEntity; 

    public ProductfeatureEntity() {
    }

    public ProductfeatureEntity(Long productId, Long featureId) {
        this.productId =productId;
        this.featureId = featureId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getFeatureId() {
        return featureId;
    }

    public void setFeatureId(Long featureId) {
        this.featureId = featureId;
    }

    public FeatureEntity getProductIdEntity() {
        return productIdEntity;
    }

    public void setProductIdEntity(FeatureEntity productIdEntity) {
        this.productIdEntity = productIdEntity;
    }

    public FeatureEntity getFeatureIdEntity() {
        return featureIdEntity;
    }

    public void setFeatureIdEntity(FeatureEntity featureIdEntity) {
        this.featureIdEntity = featureIdEntity;
    }

}
