/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.purchase.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.purchaseitem.persistence.entity.PurchaseItemEntity;
import co.edu.uniandes.csw.miso4204.purchase.persistence.entity.PurchaseEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;
import org.eclipse.persistence.annotations.Multitenant;
import org.eclipse.persistence.annotations.TenantDiscriminatorColumn;

@Entity
@Multitenant
@TenantDiscriminatorColumn(name="tenantID")
@IdClass(PurchasepurchaseItemEntityId.class)
@NamedQueries({
    @NamedQuery(name = "PurchasepurchaseItemEntity.getByMasterId", query = "SELECT  u FROM PurchasepurchaseItemEntity u WHERE u.purchaseId=:purchaseId"),
    @NamedQuery(name = "PurchasepurchaseItemEntity.deletePurchasepurchaseItemEntity", query = "DELETE FROM PurchasepurchaseItemEntity u WHERE u.purchaseId=:purchaseId and  u.purchaseItemId=:purchaseItemId")
})
public class PurchasepurchaseItemEntity implements Serializable {

    @Id
    @Column(name = "purchaseId")
    private Long purchaseId;
    @Id
    @Column(name = "purchaseItemId")
    private Long purchaseItemId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "purchaseId", referencedColumnName = "id")
    @JoinFetch
    private PurchaseItemEntity purchaseIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "purchaseItemId", referencedColumnName = "id")
    @JoinFetch
    private PurchaseItemEntity purchaseItemIdEntity; 

    public PurchasepurchaseItemEntity() {
    }

    public PurchasepurchaseItemEntity(Long purchaseId, Long purchaseItemId) {
        this.purchaseId =purchaseId;
        this.purchaseItemId = purchaseItemId;
    }

    public Long getPurchaseId() {
        return purchaseId;
    }

    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Long getPurchaseItemId() {
        return purchaseItemId;
    }

    public void setPurchaseItemId(Long purchaseItemId) {
        this.purchaseItemId = purchaseItemId;
    }

    public PurchaseItemEntity getPurchaseIdEntity() {
        return purchaseIdEntity;
    }

    public void setPurchaseIdEntity(PurchaseItemEntity purchaseIdEntity) {
        this.purchaseIdEntity = purchaseIdEntity;
    }

    public PurchaseItemEntity getPurchaseItemIdEntity() {
        return purchaseItemIdEntity;
    }

    public void setPurchaseItemIdEntity(PurchaseItemEntity purchaseItemIdEntity) {
        this.purchaseItemIdEntity = purchaseItemIdEntity;
    }

}
