/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.purchase.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.payment.persistence.entity.PaymentEntity;
import co.edu.uniandes.csw.miso4204.purchase.persistence.entity.PurchaseEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;
import org.eclipse.persistence.annotations.Multitenant;
import org.eclipse.persistence.annotations.TenantDiscriminatorColumn;

@Entity
@Multitenant
@TenantDiscriminatorColumn(name="tenantID")
@IdClass(PurchasepaymentEntityId.class)
@NamedQueries({
    @NamedQuery(name = "PurchasepaymentEntity.getByMasterId", query = "SELECT  u FROM PurchasepaymentEntity u WHERE u.purchaseId=:purchaseId"),
    @NamedQuery(name = "PurchasepaymentEntity.deletePurchasepaymentEntity", query = "DELETE FROM PurchasepaymentEntity u WHERE u.purchaseId=:purchaseId and  u.paymentId=:paymentId")
})
public class PurchasepaymentEntity implements Serializable {

    @Id
    @Column(name = "purchaseId")
    private Long purchaseId;
    @Id
    @Column(name = "paymentId")
    private Long paymentId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "purchaseId", referencedColumnName = "id")
    @JoinFetch
    private PaymentEntity purchaseIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "paymentId", referencedColumnName = "id")
    @JoinFetch
    private PaymentEntity paymentIdEntity; 

    public PurchasepaymentEntity() {
    }

    public PurchasepaymentEntity(Long purchaseId, Long paymentId) {
        this.purchaseId =purchaseId;
        this.paymentId = paymentId;
    }

    public Long getPurchaseId() {
        return purchaseId;
    }

    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Long getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    public PaymentEntity getPurchaseIdEntity() {
        return purchaseIdEntity;
    }

    public void setPurchaseIdEntity(PaymentEntity purchaseIdEntity) {
        this.purchaseIdEntity = purchaseIdEntity;
    }

    public PaymentEntity getPaymentIdEntity() {
        return paymentIdEntity;
    }

    public void setPaymentIdEntity(PaymentEntity paymentIdEntity) {
        this.paymentIdEntity = paymentIdEntity;
    }

}
