/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlistitem.persistence;

import co.edu.uniandes.csw.miso4204.wishlistitem.logic.dto.WishListItemDTO;
import co.edu.uniandes.csw.miso4204.wishlistitem.logic.dto.WishListItemPageDTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.shiro.SecurityUtils;

public class WishListItemPersistence extends _WishListItemPersistence{

    private EntityManagerFactory emf;

    public WishListItemPersistence() {
        emf = Persistence.createEntityManagerFactory("WishListItemPU");
    }
    
    public void getEntityManager() {
        co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO addressS = (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
        String tenant = addressS.getTenantID();
        Map<String, Object> emProperties = new HashMap<String, Object>();
        emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
        entityManager = emf.createEntityManager(emProperties);
    }
    
    @Override
    public WishListItemDTO createWishListItem(WishListItemDTO address) {
        WishListItemDTO address2;
        try {
            getEntityManager();
            address2 = super.createWishListItem(address);
        } catch (Exception e) {
            address2 = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address2;
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public List<WishListItemDTO> getWishListItems() {
        List<WishListItemDTO> list;
        try {
            getEntityManager();
            list = super.getWishListItems();
        } catch (Exception e) {
            list = new ArrayList<WishListItemDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public WishListItemPageDTO getWishListItems(Integer page, Integer maxRecords) {
        WishListItemPageDTO pages;
        try {
            getEntityManager();
            pages = super.getWishListItems(page, maxRecords);
        } catch (Exception e) {
            pages = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }
    
    @Override
    public WishListItemDTO getWishListItem(Long id) {
        WishListItemDTO address;
        try {
            getEntityManager();
            address = super.getWishListItem(id);
        } catch (Exception e) {
            address = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address;
    }
    
    @Override
    public void deleteWishListItem(Long id) {
        try {
            getEntityManager();
            super.deleteWishListItem(id);
        } catch (Exception e) {
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }
    
    @Override
    public void updateWishListItem(WishListItemDTO detail) {
        try {
            getEntityManager();
            super.updateWishListItem(detail);
        } catch (Exception e) {

        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }
    
    @Override
    @SuppressWarnings("unchecked")
    public List<WishListItemDTO> getTop5() {
        List<WishListItemDTO> list;
        try {
            getEntityManager();
            list = super.getTop5();
        } catch (Exception e) {
            list = new ArrayList<WishListItemDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }

}