/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.feature.persistence;

import co.edu.uniandes.csw.miso4204.feature.logic.dto.FeatureDTO;
import co.edu.uniandes.csw.miso4204.feature.logic.dto.FeaturePageDTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.shiro.SecurityUtils;

public class FeaturePersistence extends _FeaturePersistence{
        private EntityManagerFactory emf;

	public FeaturePersistence(){
		emf = Persistence.createEntityManagerFactory("FeaturePU");
	}

        public void getEntityManager() {
          co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO featureS = 
                  (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
          String tenant = featureS.getTenantID();
          Map<String, Object> emProperties = new HashMap<String, Object>();
          emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
          entityManager = emf.createEntityManager(emProperties);
        
        }

    @Override
    public FeatureDTO createFeature(FeatureDTO feature) {
        FeatureDTO feature2;
        try {
            getEntityManager();
            feature2 = super.createFeature(feature);
        } catch (Exception e) {
            e.printStackTrace();
            feature2 = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return feature2;
    }

    @Override
    @SuppressWarnings("unchecked")
    public List<FeatureDTO> getFeatures() {
        List<FeatureDTO> list;
        try {
            getEntityManager();
            list = super.getFeatures();
        } catch (Exception e) {
            e.printStackTrace();
            list = new ArrayList<FeatureDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FeaturePageDTO getFeatures(Integer page, Integer maxRecords) {
        FeaturePageDTO pages;
        try {
            getEntityManager();
            pages = super.getFeatures(page, maxRecords);
        } catch (Exception e) {
            e.printStackTrace();
            pages = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }

    @Override
    public FeatureDTO getFeature(Long id) {
        FeatureDTO feature;
        try {
            getEntityManager();
            feature = super.getFeature(id);
        } catch (Exception e) {
            e.printStackTrace();
            feature = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return feature;
    }

    @Override
    public void deleteFeature(Long id) {
        try {
            getEntityManager();
            super.deleteFeature(id);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

    @Override
    public void updateFeature(FeatureDTO detail) {
        try {
            getEntityManager();
            super.updateFeature(detail);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }        

}