/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================


 Source generated by CrudMaker version 1.0.0.qualifier

 */
package co.edu.uniandes.csw.miso4204.address.persistence;

import co.edu.uniandes.csw.miso4204.address.logic.dto.AddressDTO;
import co.edu.uniandes.csw.miso4204.address.logic.dto.AddressPageDTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.shiro.SecurityUtils;

public class AddressPersistence extends _AddressPersistence {

    private EntityManagerFactory emf;

    public AddressPersistence() {
        emf = Persistence.createEntityManagerFactory("AddressPU");
    }

    public void getEntityManager() {
        co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO addressS = (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
        String tenant = addressS.getTenantID();
        Map<String, Object> emProperties = new HashMap<String, Object>();
        emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
        entityManager = emf.createEntityManager(emProperties);
    }

    @Override
    public AddressDTO createAddress(AddressDTO address) {
        AddressDTO address2;
        try {
            getEntityManager();
            address2 = super.createAddress(address);
        } catch (Exception e) {
            e.printStackTrace();
            address2 = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address2;
    }

    @Override
    @SuppressWarnings("unchecked")
    public List<AddressDTO> getAddresss() {
        List<AddressDTO> list;
        try {
            getEntityManager();
            list = super.getAddresss();
        } catch (Exception e) {
            e.printStackTrace();
            list = new ArrayList<AddressDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AddressPageDTO getAddresss(Integer page, Integer maxRecords) {
        AddressPageDTO pages;
        try {
            getEntityManager();
            pages = super.getAddresss(page, maxRecords);
        } catch (Exception e) {
            e.printStackTrace();
            pages = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }

    @Override
    public AddressDTO getAddress(Long id) {
        AddressDTO address;
        try {
            getEntityManager();
            address = super.getAddress(id);
        } catch (Exception e) {
            e.printStackTrace();
            address = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return address;
    }

    @Override
    public void deleteAddress(Long id) {
        try {
            getEntityManager();
            super.deleteAddress(id);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

    @Override
    public void updateAddress(AddressDTO detail) {
        try {
            getEntityManager();
            super.updateAddress(detail);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

}
