/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.score.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.miso4204.score.logic.dto.ScoreDTO;
import co.edu.uniandes.csw.miso4204.score.persistence.entity.ScoreEntity;

public abstract class _ScoreConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static ScoreDTO entity2PersistenceDTO(ScoreEntity entity){
		if (entity != null) {
			ScoreDTO dto = new ScoreDTO();
					dto.setId(entity.getId());
					dto.setValue(entity.getValue());
 
			    if(entity.getDate() != null){
					dto.setDate(DATE_FORMAT.format(entity.getDate()));
				}	
					dto.setName(entity.getName());
					dto.setUserId(entity.getUserId());
					dto.setProductscoreId(entity.getProductscoreId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ScoreEntity persistenceDTO2Entity(ScoreDTO dto){
		if(dto!=null){
			ScoreEntity entity=new ScoreEntity();
					entity.setId(dto.getId());
			
					entity.setValue(dto.getValue());
			
 
			      try{ 
			        if(dto.getDate() != null){
						entity.setDate(DATE_FORMAT.parse(dto.getDate()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_ScoreConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setName(dto.getName());
			
					entity.setUserId(dto.getUserId());
			
					entity.setProductscoreId(dto.getProductscoreId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ScoreDTO> entity2PersistenceDTOList(List<ScoreEntity> entities){
		List<ScoreDTO> dtos=new ArrayList<ScoreDTO>();
		for(ScoreEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ScoreEntity> persistenceDTO2EntityList(List<ScoreDTO> dtos){
		List<ScoreEntity> entities=new ArrayList<ScoreEntity>();
		for(ScoreDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}