/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcart.master.logic.ejb;

import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.dto.ShoppingCartItemDTO;
import co.edu.uniandes.csw.miso4204.shoppingcartitem.persistence.ShoppingCartItemPersistence;

import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.master.logic.dto.ShoppingCartMasterDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.master.persistence.entity.ShoppingCartshoppingCartItemEntity;
import co.edu.uniandes.csw.miso4204.shoppingcart.persistence.ShoppingCartPersistence;
import co.edu.uniandes.csw.miso4204.shoppingcart.master.persistence.ShoppingCartMasterPersistence;


public abstract class _ShoppingCartMasterLogicService {

 
    protected ShoppingCartPersistence shoppingcartPersistance;

    protected ShoppingCartMasterPersistence shoppingcartMasterPersistance;
   
    protected ShoppingCartItemPersistence shoppingCartItemPersistance;

    public ShoppingCartMasterDTO createMasterShoppingCart(ShoppingCartMasterDTO shoppingcart) {
        ShoppingCartDTO persistedShoppingCartDTO = shoppingcartPersistance.createShoppingCart(shoppingcart.getShoppingCartEntity());
        if (shoppingcart.getCreateshoppingCartItem() != null) {
            for (ShoppingCartItemDTO shoppingCartItemDTO : shoppingcart.getCreateshoppingCartItem()) {
                ShoppingCartItemDTO createdShoppingCartItemDTO = shoppingCartItemPersistance.createShoppingCartItem(shoppingCartItemDTO);
                ShoppingCartshoppingCartItemEntity shoppingcartShoppingCartItemEntity = new ShoppingCartshoppingCartItemEntity(persistedShoppingCartDTO.getId(), createdShoppingCartItemDTO.getId());
                shoppingcartMasterPersistance.createShoppingCartshoppingCartItemEntity(shoppingcartShoppingCartItemEntity);
            }
        }
        // update shoppingCartItem
        if (shoppingcart.getUpdateshoppingCartItem() != null) {
            for (ShoppingCartItemDTO shoppingCartItemDTO : shoppingcart.getUpdateshoppingCartItem()) {
                shoppingCartItemPersistance.updateShoppingCartItem(shoppingCartItemDTO);
                ShoppingCartshoppingCartItemEntity shoppingcartShoppingCartItemEntity = new ShoppingCartshoppingCartItemEntity(persistedShoppingCartDTO.getId(), shoppingCartItemDTO.getId());
                shoppingcartMasterPersistance.createShoppingCartshoppingCartItemEntity(shoppingcartShoppingCartItemEntity);
            }
        }
        return shoppingcart;
    }

    public ShoppingCartMasterDTO getMasterShoppingCart(Long id) {
        return shoppingcartMasterPersistance.getShoppingCart(id);
    }

    public void deleteMasterShoppingCart(Long id) {
        shoppingcartPersistance.deleteShoppingCart(id);
    }

    public void updateMasterShoppingCart(ShoppingCartMasterDTO shoppingcart) {
        shoppingcartPersistance.updateShoppingCart(shoppingcart.getShoppingCartEntity());

        //---- FOR RELATIONSHIP
        // persist new shoppingCartItem
        if (shoppingcart.getCreateshoppingCartItem() != null) {
            for (ShoppingCartItemDTO shoppingCartItemDTO : shoppingcart.getCreateshoppingCartItem()) {
                ShoppingCartItemDTO createdShoppingCartItemDTO = shoppingCartItemPersistance.createShoppingCartItem(shoppingCartItemDTO);
                ShoppingCartshoppingCartItemEntity shoppingcartShoppingCartItemEntity = new ShoppingCartshoppingCartItemEntity(shoppingcart.getShoppingCartEntity().getId(), createdShoppingCartItemDTO.getId());
                shoppingcartMasterPersistance.createShoppingCartshoppingCartItemEntity(shoppingcartShoppingCartItemEntity);
            }
        }
        // update shoppingCartItem
        if (shoppingcart.getUpdateshoppingCartItem() != null) {
            for (ShoppingCartItemDTO shoppingCartItemDTO : shoppingcart.getUpdateshoppingCartItem()) {
                shoppingCartItemPersistance.updateShoppingCartItem(shoppingCartItemDTO);
            }
        }
        // delete shoppingCartItem
        if (shoppingcart.getDeleteshoppingCartItem() != null) {
            for (ShoppingCartItemDTO shoppingCartItemDTO : shoppingcart.getDeleteshoppingCartItem()) {
                shoppingcartMasterPersistance.deleteShoppingCartshoppingCartItemEntity(shoppingcart.getShoppingCartEntity().getId(), shoppingCartItemDTO.getId());
                shoppingCartItemPersistance.deleteShoppingCartItem(shoppingCartItemDTO.getId());
            }
        }
    }
}
