/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.purchase.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.miso4204.purchase.logic.dto.PurchaseDTO;
import co.edu.uniandes.csw.miso4204.purchase.master.persistence.entity.PurchaseEntity;


public abstract class _PurchaseConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static PurchaseDTO entity2PersistenceDTO(PurchaseEntity entity){
		if (entity != null) {
			PurchaseDTO dto = new PurchaseDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
 
			    if(entity.getPurchaseDate() != null){
					dto.setPurchaseDate(DATE_FORMAT.format(entity.getPurchaseDate()));
				}	
					dto.setTotalValue(entity.getTotalValue());
					dto.setTotalItems(entity.getTotalItems());
					dto.setPoints(entity.getPoints());
					dto.setBuyerId(entity.getBuyerId());
					dto.setAddressId(entity.getAddressId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static PurchaseEntity persistenceDTO2Entity(PurchaseDTO dto){
		if(dto!=null){
			PurchaseEntity entity=new PurchaseEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
 
			      try{ 
			        if(dto.getPurchaseDate() != null){
						entity.setPurchaseDate(DATE_FORMAT.parse(dto.getPurchaseDate()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_PurchaseConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setTotalValue(dto.getTotalValue());
			
					entity.setTotalItems(dto.getTotalItems());
			
					entity.setPoints(dto.getPoints());
			
					entity.setBuyerId(dto.getBuyerId());
			
					entity.setAddressId(dto.getAddressId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<PurchaseDTO> entity2PersistenceDTOList(List<PurchaseEntity> entities){
		List<PurchaseDTO> dtos=new ArrayList<PurchaseDTO>();
		for(PurchaseEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<PurchaseEntity> persistenceDTO2EntityList(List<PurchaseDTO> dtos){
		List<PurchaseEntity> entities=new ArrayList<PurchaseEntity>();
		for(PurchaseDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}