/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcart.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartPageDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.persistence.converter.ShoppingCartConverter;
import co.edu.uniandes.csw.miso4204.shoppingcart.persistence.entity.ShoppingCartEntity;

public abstract class _ShoppingCartPersistence{

  	protected EntityManager entityManager;
	
	public ShoppingCartDTO createShoppingCart(ShoppingCartDTO shoppingCart) {
		ShoppingCartEntity entity=ShoppingCartConverter.persistenceDTO2Entity(shoppingCart);
		entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
		return ShoppingCartConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ShoppingCartDTO> getShoppingCarts() {
		entityManager.getTransaction().begin();
		Query q = entityManager.createQuery("select u from ShoppingCartEntity u");
		List<ShoppingCartDTO> result = ShoppingCartConverter.entity2PersistenceDTOList(q.getResultList());
		entityManager.getTransaction().commit();
		return result;
		
	}

	@SuppressWarnings("unchecked")
	public ShoppingCartPageDTO getShoppingCarts(Integer page, Integer maxRecords) {
		entityManager.getTransaction().begin();
		Query count = entityManager.createQuery("select count(u) from ShoppingCartEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ShoppingCartEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ShoppingCartPageDTO response = new ShoppingCartPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ShoppingCartConverter.entity2PersistenceDTOList(q.getResultList()));
		entityManager.getTransaction().commit();
		return response;
	}

	public ShoppingCartDTO getShoppingCart(Long id) {
		entityManager.getTransaction().begin();
		ShoppingCartDTO result = ShoppingCartConverter.entity2PersistenceDTO(entityManager.find(ShoppingCartEntity.class, id));
		entityManager.getTransaction().commit();
		return result;
	}

	public void deleteShoppingCart(Long id) {
		entityManager.getTransaction().begin();
		ShoppingCartEntity entity=entityManager.find(ShoppingCartEntity.class, id);
		entityManager.remove(entity);
		entityManager.getTransaction().commit();
	}

	public void updateShoppingCart(ShoppingCartDTO detail) {
		entityManager.getTransaction().begin();
		ShoppingCartEntity entity=entityManager.merge(ShoppingCartConverter.persistenceDTO2Entity(detail));
		ShoppingCartConverter.entity2PersistenceDTO(entity);
		entityManager.getTransaction().commit();
	}

}