/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcart.persistence;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartPageDTO;
import org.apache.shiro.SecurityUtils;



public class ShoppingCartPersistence extends _ShoppingCartPersistence{
    
    private EntityManagerFactory emf;

    public ShoppingCartPersistence(){
        emf = Persistence.createEntityManagerFactory("ShoppingCartPU");
    }
     
    public void getEntityManager() {
        co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO addressS = (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
        String tenant = addressS.getTenantID();
        Map<String, Object> emProperties = new HashMap<String, Object>();
        emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
        entityManager = emf.createEntityManager(emProperties);
    }
        
    @Override
    public ShoppingCartDTO createShoppingCart(ShoppingCartDTO shoppingCart) {
        ShoppingCartDTO shoppingcart2;
        
        try{
            getEntityManager();
             co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO addressS = (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) SecurityUtils.getSubject().getPrincipal();
             shoppingCart.setBuyerId(addressS.getId());
            shoppingcart2 = super.createShoppingCart(shoppingCart);
            
        }
        catch (Exception e){
            e.printStackTrace();
            shoppingcart2 = null;
        }
        finally{
            if (entityManager.isOpen()){
                entityManager.close();
            }
        }
        return shoppingcart2;
    }
	
    @Override
    @SuppressWarnings("unchecked")
    public List<ShoppingCartDTO> getShoppingCarts() {
        ArrayList<ShoppingCartDTO> list;
        try{
            getEntityManager();
            list = (ArrayList<ShoppingCartDTO>) super.getShoppingCarts();
            
        }
        catch (Exception e){
            e.printStackTrace();
            list = null;
        }
        finally{
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
	return list;	
    }
    @Override
    @SuppressWarnings("unchecked")
    public ShoppingCartPageDTO getShoppingCarts(Integer page, Integer maxRecords) {
        ShoppingCartPageDTO pages;
        try{
            getEntityManager();
            pages = super.getShoppingCarts(page, maxRecords);
        }
        catch (Exception e){
            e.printStackTrace();
            pages = null;
        }
        finally{
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }
    @Override
    public ShoppingCartDTO getShoppingCart(Long id) {
        ShoppingCartDTO shoppingcart;
        try{
            getEntityManager();
            shoppingcart = super.getShoppingCart(id);
        }
        catch (Exception e){
            e.printStackTrace();
            shoppingcart = null;
        }
        finally{
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return shoppingcart;

    }
    @Override
    public void deleteShoppingCart(Long id) {
        try{
            getEntityManager();
            super.deleteShoppingCart(id);
        }
        catch (Exception e){
            e.printStackTrace();
        }
        finally{
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }
    
    @Override
    public void updateShoppingCart(ShoppingCartDTO detail) {
        try{
            getEntityManager();
            super.updateShoppingCart(detail);
        }
        catch (Exception e){
            e.printStackTrace();
        }
        finally{
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

}