/* ========================================================================
 * Copyright 2014 
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.tenantcontrol.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.tenantcontrol.logic.dto.TenantControlDTO;
import co.edu.uniandes.csw.tenantcontrol.persistence.entity.TenantControlEntity;

public abstract class _TenantControlConverter {

	public static TenantControlDTO entity2PersistenceDTO(TenantControlEntity entity){
		if (entity != null) {
			TenantControlDTO dto = new TenantControlDTO();
					dto.setId(entity.getId());
					dto.setDomain(entity.getDomain());
					dto.setState(entity.getState());
			return dto;
		}else{
			return null;
		}
	}
	
	public static TenantControlEntity persistenceDTO2Entity(TenantControlDTO dto){
		if(dto!=null){
			TenantControlEntity entity=new TenantControlEntity();
					entity.setId(dto.getId());
			
					entity.setDomain(dto.getDomain());
			
					entity.setState(dto.getState());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<TenantControlDTO> entity2PersistenceDTOList(List<TenantControlEntity> entities){
		List<TenantControlDTO> dtos=new ArrayList<TenantControlDTO>();
		for(TenantControlEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<TenantControlEntity> persistenceDTO2EntityList(List<TenantControlDTO> dtos){
		List<TenantControlEntity> entities=new ArrayList<TenantControlEntity>();
		for(TenantControlDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}