/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlist.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.wishlistitem.persistence.entity.WishListItemEntity;
import co.edu.uniandes.csw.miso4204.wishlist.persistence.entity.WishListEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;
import org.eclipse.persistence.annotations.Multitenant;
import org.eclipse.persistence.annotations.TenantDiscriminatorColumn;

@Entity
@Multitenant
@TenantDiscriminatorColumn(name="tenantID")
@IdClass(WishListwhishListItemEntityId.class)
@NamedQueries({
    @NamedQuery(name = "WishListwhishListItemEntity.getByMasterId", query = "SELECT  u FROM WishListwhishListItemEntity u WHERE u.wishListId=:wishListId"),
    @NamedQuery(name = "WishListwhishListItemEntity.deleteWishListwhishListItemEntity", query = "DELETE FROM WishListwhishListItemEntity u WHERE u.wishListId=:wishListId and  u.whishListItemId=:whishListItemId")
})
public class WishListwhishListItemEntity implements Serializable {

    @Id
    @Column(name = "wishListId")
    private Long wishListId;
    @Id
    @Column(name = "whishListItemId")
    private Long whishListItemId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "wishListId", referencedColumnName = "id")
    @JoinFetch
    private WishListItemEntity wishListIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "whishListItemId", referencedColumnName = "id")
    @JoinFetch
    private WishListItemEntity whishListItemIdEntity; 

    public WishListwhishListItemEntity() {
    }

    public WishListwhishListItemEntity(Long wishListId, Long whishListItemId) {
        this.wishListId =wishListId;
        this.whishListItemId = whishListItemId;
    }

    public Long getWishListId() {
        return wishListId;
    }

    public void setWishListId(Long wishListId) {
        this.wishListId = wishListId;
    }

    public Long getWhishListItemId() {
        return whishListItemId;
    }

    public void setWhishListItemId(Long whishListItemId) {
        this.whishListItemId = whishListItemId;
    }

    public WishListItemEntity getWishListIdEntity() {
        return wishListIdEntity;
    }

    public void setWishListIdEntity(WishListItemEntity wishListIdEntity) {
        this.wishListIdEntity = wishListIdEntity;
    }

    public WishListItemEntity getWhishListItemIdEntity() {
        return whishListItemIdEntity;
    }

    public void setWhishListItemIdEntity(WishListItemEntity whishListItemIdEntity) {
        this.whishListItemIdEntity = whishListItemIdEntity;
    }

}
