/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.creditcard.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.miso4204.creditcard.logic.dto.CreditCardDTO;
import co.edu.uniandes.csw.miso4204.creditcard.persistence.entity.CreditCardEntity;

public abstract class _CreditCardConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static CreditCardDTO entity2PersistenceDTO(CreditCardEntity entity){
		if (entity != null) {
			CreditCardDTO dto = new CreditCardDTO();
					dto.setCardNumber(entity.getCardNumber());
 
			    if(entity.getExpirationDate() != null){
					dto.setExpirationDate(DATE_FORMAT.format(entity.getExpirationDate()));
				}	
					dto.setCvc(entity.getCvc());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setBranch(entity.getBranch());
					dto.setAccountType(entity.getAccountType());
			return dto;
		}else{
			return null;
		}
	}
	
	public static CreditCardEntity persistenceDTO2Entity(CreditCardDTO dto){
		if(dto!=null){
			CreditCardEntity entity=new CreditCardEntity();
					entity.setCardNumber(dto.getCardNumber());
			
 
			      try{ 
			        if(dto.getExpirationDate() != null){
						entity.setExpirationDate(DATE_FORMAT.parse(dto.getExpirationDate()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_CreditCardConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setCvc(dto.getCvc());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setBranch(dto.getBranch());
			
					entity.setAccountType(dto.getAccountType());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<CreditCardDTO> entity2PersistenceDTOList(List<CreditCardEntity> entities){
		List<CreditCardDTO> dtos=new ArrayList<CreditCardDTO>();
		for(CreditCardEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<CreditCardEntity> persistenceDTO2EntityList(List<CreditCardDTO> dtos){
		List<CreditCardEntity> entities=new ArrayList<CreditCardEntity>();
		for(CreditCardDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}