/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.product.master.persistence;
import co.edu.uniandes.csw.miso4204.picture.logic.dto.PictureDTO;
import co.edu.uniandes.csw.miso4204.product.master.persistence.entity.ProductpictureEntity;
import co.edu.uniandes.csw.miso4204.picture.persistence.converter.PictureConverter;
import co.edu.uniandes.csw.miso4204.feature.logic.dto.FeatureDTO;
import co.edu.uniandes.csw.miso4204.product.master.persistence.entity.ProductfeatureEntity;
import co.edu.uniandes.csw.miso4204.feature.persistence.converter.FeatureConverter;
import co.edu.uniandes.csw.miso4204.product.logic.dto.ProductDTO;
import co.edu.uniandes.csw.miso4204.product.master.logic.dto.ProductMasterDTO;
import co.edu.uniandes.csw.miso4204.product.persistence.ProductPersistence;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;

public class _ProductMasterPersistence{

    protected EntityManager entityManager;
    
    protected ProductPersistence productPersistence;  

    public ProductMasterDTO getProduct(Long productId) {
        ProductMasterDTO productMasterDTO = new ProductMasterDTO();
        ProductDTO product = productPersistence.getProduct(productId);
        productMasterDTO.setProductEntity(product);
        productMasterDTO.setListpicture(getProductpictureEntityList(productId));
        productMasterDTO.setListfeature(getProductfeatureEntityList(productId));
        return productMasterDTO;
    }

    public ProductpictureEntity createProductpictureEntity(ProductpictureEntity entity) {
        entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
        return entity;
    }

   public void deleteProductpictureEntity(Long productId, Long pictureId) {
		entityManager.getTransaction().begin();
        Query q = entityManager.createNamedQuery("ProductpictureEntity.deleteProductpictureEntity");
        q.setParameter("productId", productId);
        q.setParameter("pictureId", pictureId);
        q.executeUpdate();
		entityManager.getTransaction().commit();
    }

   public List<PictureDTO> getProductpictureEntityList(Long productId) {
		entityManager.getTransaction().begin();
		ArrayList<PictureDTO> resp = new ArrayList<PictureDTO>();
        Query q = entityManager.createNamedQuery("ProductpictureEntity.getByMasterId");
        q.setParameter("productId",productId);
        List<ProductpictureEntity> qResult =  q.getResultList();
        for (ProductpictureEntity entity : qResult) { 
            if(entity.getPictureIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(PictureConverter.entity2PersistenceDTO(entity.getPictureIdEntity()));
        }
        entityManager.getTransaction().commit();
        return resp;
      
    }
    public ProductfeatureEntity createProductfeatureEntity(ProductfeatureEntity entity) {
        entityManager.getTransaction().begin();
		entityManager.persist(entity);
		entityManager.getTransaction().commit();
        return entity;
    }

   public void deleteProductfeatureEntity(Long productId, Long featureId) {
		entityManager.getTransaction().begin();
        Query q = entityManager.createNamedQuery("ProductfeatureEntity.deleteProductfeatureEntity");
        q.setParameter("productId", productId);
        q.setParameter("featureId", featureId);
        q.executeUpdate();
		entityManager.getTransaction().commit();
    }

   public List<FeatureDTO> getProductfeatureEntityList(Long productId) {
		entityManager.getTransaction().begin();
		ArrayList<FeatureDTO> resp = new ArrayList<FeatureDTO>();
        Query q = entityManager.createNamedQuery("ProductfeatureEntity.getByMasterId");
        q.setParameter("productId",productId);
        List<ProductfeatureEntity> qResult =  q.getResultList();
        for (ProductfeatureEntity entity : qResult) { 
            if(entity.getFeatureIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(FeatureConverter.entity2PersistenceDTO(entity.getFeatureIdEntity()));
        }
        entityManager.getTransaction().commit();
        return resp;
      
    }
 
}