/* ========================================================================
   * Copyright 2014 miso4204
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 miso4204
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.miso4204.bonus.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.miso4204.bonus.logic.dto.BonusDTO;
import co.edu.uniandes.csw.miso4204.bonus.persistence.entity.BonusEntity;

public abstract class _BonusConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static BonusDTO entity2PersistenceDTO(BonusEntity entity){
		if (entity != null) {
			BonusDTO dto = new BonusDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDescription(entity.getDescription());
					dto.setValue(entity.getValue());
					dto.setStatus(entity.getStatus());
 
			    if(entity.getDate() != null){
					dto.setDate(DATE_FORMAT.format(entity.getDate()));
				}	
 
			    if(entity.getExpiration() != null){
					dto.setExpiration(DATE_FORMAT.format(entity.getExpiration()));
				}	
					dto.setBuyerId(entity.getBuyerId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static BonusEntity persistenceDTO2Entity(BonusDTO dto){
		if(dto!=null){
			BonusEntity entity=new BonusEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDescription(dto.getDescription());
			
					entity.setValue(dto.getValue());
			
					entity.setStatus(dto.getStatus());
			
 
			      try{ 
			        if(dto.getDate() != null){
						entity.setDate(DATE_FORMAT.parse(dto.getDate()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_BonusConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
 
			      try{ 
			        if(dto.getExpiration() != null){
						entity.setExpiration(DATE_FORMAT.parse(dto.getExpiration()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_BonusConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setBuyerId(dto.getBuyerId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<BonusDTO> entity2PersistenceDTOList(List<BonusEntity> entities){
		List<BonusDTO> dtos=new ArrayList<BonusDTO>();
		for(BonusEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<BonusEntity> persistenceDTO2EntityList(List<BonusDTO> dtos){
		List<BonusEntity> entities=new ArrayList<BonusEntity>();
		for(BonusDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}