/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.category.persistence;

import co.edu.uniandes.csw.miso4204.category.logic.dto.CategoryDTO;
import co.edu.uniandes.csw.miso4204.category.logic.dto.CategoryPageDTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.shiro.SecurityUtils;

public class CategoryPersistence extends _CategoryPersistence{
        private EntityManagerFactory emf;
	public CategoryPersistence(){
                emf = Persistence.createEntityManagerFactory("CategoryPU");
	}
        
        public void getEntityManager() {
          co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO categoryS = 
                  (co.edu.uniandes.csw.miso4204.security.logic.dto.UserDTO) 
                  SecurityUtils.getSubject().getPrincipal();
          String tenant = categoryS.getTenantID();
          Map<String, Object> emProperties = new HashMap<String, Object>();
          emProperties.put("eclipselink.tenant-id", tenant);//Asigna un valor al multitenant
          entityManager = emf.createEntityManager(emProperties);
        }

        
    @Override
    public CategoryDTO createCategory(CategoryDTO category) {
        CategoryDTO category2;
        try {
            getEntityManager();
            category2 = super.createCategory(category);
        } catch (Exception e) {
            e.printStackTrace();
            category2 = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return category2;
    }

    @Override
    @SuppressWarnings("unchecked")
    public List<CategoryDTO> getCategorys() {
        List<CategoryDTO> list;
        try {
            getEntityManager();
            list = super.getCategorys();
        } catch (Exception e) {
            e.printStackTrace();
            list = new ArrayList<CategoryDTO>();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return list;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CategoryPageDTO getCategorys(Integer page, Integer maxRecords) {
        CategoryPageDTO pages;
        try {
            getEntityManager();
            pages = super.getCategorys(page, maxRecords);
        } catch (Exception e) {
            e.printStackTrace();
            pages = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return pages;
    }

    @Override
    public CategoryDTO getCategory(Long id) {
        CategoryDTO category;
        try {
            getEntityManager();
            category = super.getCategory(id);
        } catch (Exception e) {
            e.printStackTrace();
            category = null;
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
        return category;
    }

    @Override
    public void deleteCategory(Long id) {
        try {
            getEntityManager();
            super.deleteCategory(id);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }

    @Override
    public void updateCategory(CategoryDTO detail) {
        try {
            getEntityManager();
            super.updateCategory(detail);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }
        }
    }        
}