/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcart.master.persistence.entity;

import co.edu.uniandes.csw.miso4204.shoppingcartitem.persistence.entity.ShoppingCartItemEntity;
import co.edu.uniandes.csw.miso4204.shoppingcart.persistence.entity.ShoppingCartEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ShoppingCartshoppingCartItemEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ShoppingCartshoppingCartItemEntity.getByMasterId", query = "SELECT  u FROM ShoppingCartshoppingCartItemEntity u WHERE u.shoppingCartId=:shoppingCartId"),
    @NamedQuery(name = "ShoppingCartshoppingCartItemEntity.deleteShoppingCartshoppingCartItemEntity", query = "DELETE FROM ShoppingCartshoppingCartItemEntity u WHERE u.shoppingCartId=:shoppingCartId and  u.shoppingCartItemId=:shoppingCartItemId")
})
public class ShoppingCartshoppingCartItemEntity implements Serializable {

    @Id
    @Column(name = "shoppingCartId")
    private Long shoppingCartId;
    @Id
    @Column(name = "shoppingCartItemId")
    private Long shoppingCartItemId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "shoppingCartId", referencedColumnName = "id")
    @JoinFetch
    private ShoppingCartItemEntity shoppingCartIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "shoppingCartItemId", referencedColumnName = "id")
    @JoinFetch
    private ShoppingCartItemEntity shoppingCartItemIdEntity; 

    public ShoppingCartshoppingCartItemEntity() {
    }

    public ShoppingCartshoppingCartItemEntity(Long shoppingCartId, Long shoppingCartItemId) {
        this.shoppingCartId =shoppingCartId;
        this.shoppingCartItemId = shoppingCartItemId;
    }

    public Long getShoppingCartId() {
        return shoppingCartId;
    }

    public void setShoppingCartId(Long shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }

    public Long getShoppingCartItemId() {
        return shoppingCartItemId;
    }

    public void setShoppingCartItemId(Long shoppingCartItemId) {
        this.shoppingCartItemId = shoppingCartItemId;
    }

    public ShoppingCartItemEntity getShoppingCartIdEntity() {
        return shoppingCartIdEntity;
    }

    public void setShoppingCartIdEntity(ShoppingCartItemEntity shoppingCartIdEntity) {
        this.shoppingCartIdEntity = shoppingCartIdEntity;
    }

    public ShoppingCartItemEntity getShoppingCartItemIdEntity() {
        return shoppingCartItemIdEntity;
    }

    public void setShoppingCartItemIdEntity(ShoppingCartItemEntity shoppingCartItemIdEntity) {
        this.shoppingCartItemIdEntity = shoppingCartItemIdEntity;
    }

}
