/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.product.persistence;

import co.edu.uniandes.csw.miso4204.product.logic.dto.ProductDTO;
import co.edu.uniandes.csw.miso4204.product.logic.dto.ProductPageDTO;
import co.edu.uniandes.csw.miso4204.product.persistence.converter.ProductConverter;
import co.edu.uniandes.csw.miso4204.product.persistence.entity.ProductEntity;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

public class ProductPersistence extends _ProductPersistence{

	public ProductPersistence(){
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProductPU");
		entityManager = emf.createEntityManager();
	}

        
        
        public List<ProductDTO> getProducts(Long category, 
                                            Long feature, 
                                            String searchText, 
                                            String strMaxRecords, 
                                            String strFirstRecord) 
        {
               return this.getProductsSearch(category, feature, null, null, 
                                       searchText, 
                                       new Integer(strMaxRecords), 
                                       new Integer(strFirstRecord));
        }
        
        public List<ProductDTO> getProducts(Long category, 
                                            Long feature, 
                                            String searchText, 
                                            Integer maxRecords, 
                                            Integer firstRecord) 
        {
               return this.getProductsSearch(category, feature, null, null, searchText, maxRecords, firstRecord);
        }

        public List<ProductDTO> getProductsSearch(Long category, 
                                            Long feature, 
                                            Double minPrice,
                                            Double maxPrice,
                                            String searchText, 
                                            Integer maxRecords, 
                                            Integer firstRecord) 
        {
                // Armar la sentencia SQL
            
            
                String sqlStatement = " select u.id, u.name, u.description, u.price, u.categoryId from ProductEntity u ";
                if (feature != null) {
                    sqlStatement += " , ProductFeatureEntity pf " +
                                    " where u.id = pf.productid " +
                                    "   and pf.featureid = " + feature;                           
                }
                else {
                    sqlStatement += " where 1=1 ";
                }
                
                if (category != null) {
                    sqlStatement += " and u.categoryid = " + category;
                }
                
                if (minPrice != null) {
                    sqlStatement += " and u.price >= " + minPrice;
                }
                if (maxPrice != null) {
                    sqlStatement += " and u.price <= " + maxPrice;
                }
                if (searchText != null) {
                    sqlStatement += " and lower(u.description) like '%" + searchText.trim().toLowerCase() + "%' ";
                }
               
		//entityManager.getTransaction().begin();

                Query q = entityManager.createNativeQuery(sqlStatement, ProductEntity.class);
		if (firstRecord != null && maxRecords != null && firstRecord.compareTo(new Integer(0))>0) {
		    q.setFirstResult(firstRecord);
		    q.setMaxResults(maxRecords);
		}        
		List<ProductDTO> result = ProductConverter.entity2PersistenceDTOList(q.getResultList());
		//entityManager.getTransaction().commit();
		return result;
        }
}