/* ========================================================================
   * Copyright 2014 miso4204
   *
   * Licensed under the MIT, The MIT License (MIT)
   * Copyright (c) 2014 miso4204
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
   * ========================================================================
  
  
  Source generated by CrudMaker version 1.0.0.201410261249*/

package co.edu.uniandes.csw.miso4204.bonus.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.miso4204.bonus.logic.dto.BonusDTO;
import co.edu.uniandes.csw.miso4204.bonus.logic.dto.BonusPageDTO;
import co.edu.uniandes.csw.miso4204.bonus.persistence.api._IBonusPersistence;
import co.edu.uniandes.csw.miso4204.bonus.persistence.converter.BonusConverter;
import co.edu.uniandes.csw.miso4204.bonus.persistence.entity.BonusEntity;

public abstract class _BonusPersistence implements _IBonusPersistence {

  	@PersistenceContext(unitName="marketplacesplPU")
 
	protected EntityManager entityManager;
	
	public BonusDTO createBonus(BonusDTO bonus) {
		BonusEntity entity=BonusConverter.persistenceDTO2Entity(bonus);
		entityManager.persist(entity);
		return BonusConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<BonusDTO> getBonuss() {
		Query q = entityManager.createQuery("select u from BonusEntity u");
		return BonusConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public BonusPageDTO getBonuss(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from BonusEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from BonusEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		BonusPageDTO response = new BonusPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(BonusConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public BonusDTO getBonus(Long id) {
		return BonusConverter.entity2PersistenceDTO(entityManager.find(BonusEntity.class, id));
	}

	public void deleteBonus(Long id) {
		BonusEntity entity=entityManager.find(BonusEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateBonus(BonusDTO detail) {
		BonusEntity entity=entityManager.merge(BonusConverter.persistenceDTO2Entity(detail));
		BonusConverter.entity2PersistenceDTO(entity);
	}

}